#!/bin/bash
#^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^
#    Name: $HOME/.bashrc
# Summary: bash shell config for at least Cygwin 1.3/1.5/1.7, Unix and z/OS
#
#  Created: Tue 19 May 1998 08:21:18 (Bob Heckel)
# Modified: Sat 18 Jan 2014 11:33:54 (Bob Heckel)
#^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^

#----------------
# Generic  #{{{1 
#----------------
# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
###if [[ $- != *i* ]] ; then
	# Shell is non-interactive
###	return
###fi
[[ $- != *i* ]] && return

# One arg per call
set -o vi  # what's an emac...?
set -o noclobber

# C-S suspended C-Q released fix
stty -ixon 

#-----------------------
# Generic Export  #{{{2
#-----------------------
export EDITOR=vi
export HISTFILESIZE=50000  # max lines in $HISTFILE
export HISTIGNORE='f:fg:l:ls:la:cd:h:ll::d:by:&'  # '&' supposedly same as HISTCONTROL=ignoredups - consecutive dups that is
# No duplicates, no same successive entries ('&' HISTIGNORE doesn't work 2007-11-18)
export HISTCONTROL=ignoreboth
export HISTTIMEFORMAT='%F %T '
export IGNOREEOF=1  # require 2 ctr-d to exit
# More portable than the cleaner  if [ "${OSTYPE:0:6}" = 'CYGWIN' ]; then ...
###export ISCYG=`echo ${OSTYPE} | /usr/bin/perl -pe 's/(.{6}).*/$1/'`
# Prevent ugly default bolding
export LS_COLORS='*.swp=00;35:*.swo=00;35:*.bak=00;35:ex=00;32:*.java=00;32:*.pm=00;32:no=00:fi=00:di=01;34:ln=00;36:*.lnk=00;36:*.gz=00;31:*.bz2=00;31:*.zip=00;31:*.tgz=00;31:*.7z=00;31'
export PAGER=less  # for man(1)
export PARINIT='rTbgqR B=.?_A_a Q=_s>| w65'  # par formatter
export TMP=$HOME/tmp
# Default "unknown host" indicator for my .vimrc statusline
export VIMSTATUSL='?@?'

GREP_OPTIONS=
if grep --help | grep -- --exclude-dir &>/dev/null; then
  for PATTERN in .cvs .git .hg .svn; do
    GREP_OPTIONS="$GREP_OPTIONS --exclude-dir=$PATTERN"
  done
fi
export GREP_OPTIONS

# Used by at least PS1, also good for use in shell scripts.  But bad for when printing env
# Ctrl-v escape to insert the ^[
export fg_whitebold="[1;37m"
export fg_black="[0;30m"
export fg_lightgray="[0;37m"
export fg_darkgray="[1;30m"
export fg_bluebold="[1;34m"
export fg_blue="[0;34m"
export fg_greenbold="[1;32m"
export fg_green="[0;32m"
export fg_cyanbold="[1;36m"
export fg_cyan="[0;36m"
export fg_redbold="[1;31m"
export fg_red="[0;31m"
export fg_purplebold="[1;35m"
export fg_purple="[0;35m"
export fg_yellowbold="[1;33m"
export fg_yellow="[0;33m"
export normal="[0m"

#-----------------------
# Generic Alias	 #{{{2
#-----------------------
alias ..='cd ..'
alias bc="bc -lq"  # allow floating point calcs
alias be="vi $HOME/code/misccode/_bashrc"
alias bak="$HOME/code/misccode/bak"
alias bgrep="$HOME/code/perl/bgrep"
alias by=exit  # like bye in FTP and SAS
alias cd..='cd ..; ls'
alias cdc="cd $HOME/code/c"
alias cdh="cd $HOME/code/html"
alias cdm="cd $HOME/code/misccode"
alias cdp="cd $HOME/code/perl"
alias cdpl="cd $HOME/code/perl"
alias cdt="cd $HOME/tmp"
alias cds="cd $HOME/code/sas"
alias cdv="cd $HOME/code/vb"
alias cdvb="cd $HOME/code/vb"
alias cls=clear  # like Windows
alias f='fg'  # jobs -s  to list what's suspended
alias g=$HOME/code/misccode/gone.sh
alias gb='git branch -v; echo "MRU:"; git for-each-ref --sort=-committerdate refs/heads/ --format="%(committerdate:short) %(authorname) %(refname:short)" | head -n5'
# * e853f54 1 year, 4 months ago | 1st commit  [Bob Heckel]
alias gl='git log --pretty=format:"%Cblue%h %ar |%Cgreen %s%Cblue %d [%an]" --graph --date=short'
alias gs='git status'
alias h='history|tail -20'  # history 20 is better if it exists
alias iv=vi
alias j="jobs -s"  # only show STOPPED (i.e. skip RUNNING blink.exe's) jobs
alias l='ls'
# Overridden later if non-GNU ls is present.  Do not move.
alias la='ls -FA --color=auto'
###alias ls='ls --color --group-directories-first'
###alias ll='ls -lh'
alias ll='ls -gGh --color --group-directories-first'
# If ls -lS isn't available:
###alias lls='ls -l | sort +4r | grep -v "total"'  # sort descending on size
alias lsd='find . -type d'
alias locate='locate -i'
###alias m=more
alias one="vi $HOME/code/misccode/oneliners"
# Case insensitive search for module:
###alias pdoc='perldoc -i'     
alias plinstall='perl Makefile.PL && make && make TEST_VERBOSE=1 test && make install'
alias qr=$HOME/code/misccode/quickref_find.sh
alias rme=$HOME/code/misccode/rme
###alias r='fc -s'  # reexecute last command beginning with $1
alias robots="export ROBOTOPTS=moveheaps,showscores,screwdriver,fastrobots; robots"
# sdf.freeshell.org
alias sdf='ssh -l bheckel sdf.org; date'
alias sl='ls --color=none'  # dyslexic daim branage
alias sr="$HOME/code/sas/sasrun"
alias srcb="source $HOME/code/misccode/_bashrc"
alias unbak="$HOME/code/misccode/bak -u "
alias ve="vi $HOME/code/misccode/_vimrc"
alias wget='wget -c'  # continue failures

#-----------------------------------
# bash functions must precede calls
# Generic Functions  #{{{2
#-----------------------------------

cdl(){ cd "$@" && ls;}


# Avoid garbage on the command line.   .vimrc has a similar function.
# E.g. run prior to doing a $ su foouser
fix() {
  unset PROMPT_COMMAND
  unset PS1
  export PS1='\u@\h\$ '  # generic
  export TERM=vt100  # guessing that we're coming in via telnet
}


# Used with PS1 as an exit value indicator.
# Don't use this for non-color xterms and when xtrace is in use.  See fix().
# TODO not working, $? is always 0
# Unused 2010-11-28
###set_prompt_colors() {
###  if (( errornum = $? )); then
###    prompt_beg="${fg_redbold}"
###    prompt_end="${normal}"
###  else
###    if test "$HOSTNAME" = 'sverige' || test "$HOSTNAME" = 'sdf'; then
###      prompt_beg="${fg_whitebold}"
###    elif test "$HOSTNAME" = 'tstdev'; then
###      prompt_beg="${fg_cyanbold}"
###    else
###      prompt_beg="${fg_greenbold}"
###    fi
###    prompt_beg=$fg_greenbold
###    prompt_end=$normal
###  fi
###}


# 'start' a file or file manager
st() {
  if [ $# = 0 ]; then
    if [ $OSTYPE = 'cygwin' ];then
      cygstart -x "$PWD"
    else
      xdg-open
    fi
  else
    if [ $OSTYPE = 'cygwin' ];then
      cygstart "$1"
    else
      xdg-open "$1" &
    fi
  fi
}


# Recycler to ReMoVe files we're not yet ready to delete.
# TODO call underscore() if necessary first
# TODO allow run from other than pwd
# TODO don't write a partial REMOVETHIS__ on failure
# TODO make sure user is in the dir if -s is used
rmv() {
  local VERBOSE
  local MARKER
  local __TMP

  # MUST be same as in ~/bin/clean_synch
  MARKER=REMOVETHIS__
  # Don't want /tmp as the rmv dir so change it if necessary
  __TMP=$TMP
  [ "$__TMP" = /tmp ] && __TMP=/$USER/tmp
  [ "$__TMP" = //tmp ] && __TMP=/$USER/tmp # double slash is due to root's home '/'
  [ "$__TMP" = '' ] && __TMP=/$USER/tmp
  [ "$__TMP" = / ] && __TMP=/$USER/tmp

  # -s placeholder file output is used for synching parsifal and work PC's
  # important directories.
  if [ ! "$1" ]; then
    echo 'error: Must enter file(s) or file pattern.  Exiting.'
    echo 'Usage: rmv [-s|-v] file1 file2 pat* ...'
    echo "       Removes a file or files to $HOME/tmp"
    echo "       -s places a $MARKER marker after rmv'ing (sweep-away-sync mode)"
    echo "          Must be in pwd for this command to place marker properly"
    echo "       -v verbose mode"
    return 1
  fi
  if [ "$1" = '-s' ]; then
    shift
    for f in "$@"; do
      touch "${MARKER}${f}"
    done
  fi
  if [ "$1" = '-v' ]; then
    VERBOSE=$1
    shift
  else
    VERBOSE=''
  fi
  if [ -d $__TMP ]; then
    for f in "$@"; do
      mv $VERBOSE "$f" $__TMP || echo 'failed to rmv'
    done
  else  # rare
    echo "uh oh we're missing $HOME/tmp ...";
		echo "...attempting to mkdir, please fix manually if there is no success message below"
		mkdir $HOME/tmp
		if [ -e $HOME/tmp ]; then
		  echo "...success"
		else
		  echo "cannot create $HOME/tmp"
		fi
  fi
}


# TODO not working - just using gt alias against a hardcoded .go.uniq.txt for now
# 1) cd //Rtpdsntp032/DataPostArchive/DataPost/zip_files # prod 
# 2) cd //Rtpdsntp032/DataPostArchive/Serevent_Diskus/CODE # prod prd 
# 3) cd //Rtpdsntp032/DataPostArchive/Valtrex_Caplets/CODE # prod prd 
#
# Improvement to pushd and cdargs
###go() {
###  local dat="$HOME/.go.txt"
###  local datcore="$HOME/.go.core.txt"  # never overwritten if exists
###  local datuniq="$HOME/.go.uniq.txt"
###  local maxvolatilenames=20
###  local maxvolatilenames2=`expr $maxvolatilenames + 1`
###
###  # Make dummy to avoid errors if doesn't exist
###  if [ ! -e "$datcore" ]; then
###    touch $datcore
###    echo "go's core datafile ($datcore) is non-existent, dummy created"
###  fi
###
###  # Switch-less lists available dirs, if any, from previous runs
###  if [ "$#" -eq 0 ]; then
###    if [ -e "$datuniq" ]; then
###      # Eliminate the leading "cd"s only for readability
###      cat "$datuniq" | sed 's/cd//'
###      return 0
###    else
###      echo "go's datafile ($datuniq) is non-existent"
###      return 0
###    fi
###  elif [ "$#" -ge 1 ]; then
###    while getopts cdth the_opt; do
###      case "$the_opt" in
###        c ) # Remove dead dirs requested
###            goclean
###            unset OPTIND
###            return 0
###            ;;
###        d ) # Tempfile deletion requested
###            rm "$dat" 
###            rm "$datuniq" 
###            unset OPTIND
###            return 0 
###            ;;
###        h ) 
###            echo 'Simple directory navigation to previously saved dirs'
###            echo 'Usage: go [ N | DIR-TO-SAVE-THEN-CD-TO ] [ -c -d -h ]'
###            echo '  -c run goclean() to remove nonexistent directories'
###            echo '  -d delete working files (no prompts)'
###            echo '  -h this help message'
###            unset OPTIND
###            return 0 
###            ;;
###        # Go [t]o the most likely dir if it is unique enough.  S/b aliased as
###        # 'gt' for speed.
###        t ) 
###            # Count lines matching via -c
###            if [ `grep -ic "$2" "$datuniq"` -eq 1 ]; then
###              # Found one match only
###              # Go to the only choice (we're taking advantage of the leading
###              # "cd" in go.uniq.tmp.txt) after removing our leading numbers.
###              if [ "$ISCYG" = 'CYGWIN' ]; then
###                # Minor ')' enhancement
###                ###`grep -i "$2" "$datuniq" | sed "s/[0-9])//"`
###                `grep -i "$2" "$datuniq" | sed 's/....//'`
###                unset OPTIND
###                return 0
###              else
###                echo 'not implemented'
###              fi
###            elif [ `grep -ic "$2" "$datuniq"` -gt 1 ]; then
###              # Ambiguous - show matches, let user decide
###              grep -i "$2" "$datuniq"
###              unset OPTIND
###	      echo -n '? '
###	      read whereto
###              # Recursive
###	      go $whereto
###              return 0
###            else
###              # Found nothing, show all to prove it
###              cat "$datuniq"
###              unset OPTIND
###              return 0
###            fi
###            return 0 
###            ;;
###      esac
###    done
###  fi
###  # Fall-thru -- navigation digit passed:
###  case "$1" in
###    1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 ) 
###      # cd to dirs numbered 1 thru max of 9.  
###      # Column positions of the tmp file are important.
###      if [ "$ISCYG" = 'CYGWIN' ]; then
###        `cat $datuniq | grep "^ \+$1" | sed 's/^...//'`
###        unset OPTIND
###        return 0
###      fi
###    ;;
###    # This max must be same as tail parameter below plus the number of lines in
###    # $datcore (or we must delete rows from .go.txt)
###    10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 | 31 | 32 | 33 | 34 | 35 | 36 | 37 | 38 | 39 | 40 | 41 | 42 | 43 | 44 | 45 | 46 | 47 | 48 | 49 | 50 | 51 | 52 | 53 | 54 | 55 | 56 | 57 | 58 | 59 | 60 | 61 | 62 | 63 | 64 | 65 | 66 | 67 | 68 | 69 | 70 ) 
###      # Column positions of the tmp file are important.
###      if [ "$ISCYG" = 'CYGWIN' ]; then
###        # TODO spaces in path - this resolves to
###        # cd /cygdrive/c/Documents\ and\ Settings/rsh86800/My\ Documents
###        # but then cd fails to cd to it
###        `cat $datuniq | grep "^$1" | sed 's/^...//'`
###        unset OPTIND
###        return 0
###      fi
###    ;;
###    * ) 
###      # User wants to add a new go() dir but we'll test that it exists
###      # first.  cd(1) gives warning on failure so we won't add any here.
###      if ( cd "$1" ); then
###        cd "$1"
###        d="$PWD"
###        # Lastest saves are at bottom
###        echo "cd $d" | sed -e 's/ /\\ /g' -e 's/cd\\/cd/g' >> $dat
###        # Take a slice from the bottom of the file after removing dups
###        if [ "$ISCYG" = 'CYGWIN' ]; then
###          tail -$maxvolatilenames $dat | sort | uniq -i | nl -w2 -nrn -s') ' >| $datuniq
###          # Always want these  TODO avoid dups in core & uniq .go's
###          cat $datcore | sort | uniq -i | nl -v$maxvolatilenames2 -w2 -nrn -s') ' >> $datuniq
###        else
###          ###tail -$maxvolatilenames $dat | sort | uniq | nl >| $datuniq
###          echo 'not implemented'
###        fi
###        unset OPTIND
###        return 0
###      fi
###    ;;
###  esac
###}

# Cleanup the working files of go() by verifying existence of dirs.
# Usually called via go -c.  Separate from go() to allow easier refreshing of
# the datafiles.
# TODO chokes on paths with spaces "bash: [: /c/Program: binary operator
# expected"
###goclean() {
###  local dat=$HOME/.go.txt
###  local datuniq="$HOME/.go.uniq.txt"
###  local datmp=$TMP/cleango$$
###  local maxlines=75
###
###  >$datmp
###
###  while read l; do 
###    # Remove 'cd ' part of line used by go()
###    m=`echo "$l" | sed 's/^[^/]*//'`
###    # Keep dirs that still exist since original call to go()
###    if [ -d "$m" ]; then
###      echo $l >>$datmp
###    fi
###  done <$dat
###
###  cat $datmp | uniq | tail -$maxlines >| $dat
###
###  if [ "$ISCYG" = 'CYGWIN' ]; then
###    tail -9 "$dat" | sort | uniq | nl -w2 -nrn -s') ' >| "$datuniq"
###  else
###    tail -9 "$dat" | sort | uniq | nl >| "$datuniq"
###  fi
###
###  rm $datmp
###}


# Adapted from http://hermitte.free.fr/cygwin/#Win32
# Shortcuts + better presentation of the directories pushed.
# Display the directories pushed
d() {
  \dirs | awk  '{gsub(/ ~/, "!~"); gsub(/ \//, "!/") ; n=split($0,arr,"!") ; 
  for (i=1;i<=n;++i) print (i-1)" -> "arr[i] }'
}
# Note: We can not directly write «dirs() { \dirs | ... }» as it would
# end in an infinite loop. Hence the declaration of «d(){}» and dirs as
# an alias for d.
alias dirs=d

# Push a directory
p() {
  # The quotes in «"$*» permit to write «p $vim»
  \pushd "$*" > /dev/null
	# List the directories pushed
	d
}
# Move to a pushed directory
alias p1="p +1"
alias p2="p +2"
alias p3="p +3"
alias p4="p +4"
alias p5="p +5"


# For PROMPT_COMMAND.  22-Mar-11 obsolete, use \j where possible
stoppedjobs() { 
  jobs -s | wc -l | sed -e "s/ //g" 
}


# Latest twenty
###lt() {
###  if test "x$1" = "x"; then
###    \ls -ltG --color=none | head -n20
###  else
###    \ls -ltG --color=none "$1" | head -n20
###  fi
###}


# Super-search
###ss() {
###  ( 
###  if [ "x$1" != "x" ]; then
###    $HOME/bin/gone "$1" "$2"
###    loc "$1" "$2"
###  else
###    echo 'usage: ss findme [s|p]'
###    echo '       searches using gone and loc, optionally using proglang type restriction'
###  fi
###  )
###}


# Build a fast, disposable sandbox for testing
sbx() {
  # Leading epoch date for sorting purposes
  todayuniq=`date +%s_%d%b%y`$1
  mkdir $HOME/tmp/$todayuniq
  cd $HOME/tmp/$todayuniq
}


lt() {
  if test "x$1" = "x"; then
    \ls -lt | head -n25
  else
    \ls -lt "$1" | head -n25
  fi
}


# Fast navigation to recent directories.  Assumes you'll often use my vim map ;w from within fc.
# E.g.
# $ to  # '$ to var' would shorten this list
# cd $c/datapost
# cd $c/temp
# cd /cygdrive/c/datapost
# cd /var
#  note: /cygdrive/u/temp/.vimxfer loaded  # then fc and ;w to reach one of these dirs
# 
# May be easier just to "tag" a dir via $ cd /foo  # my foo breadcrumb
to() {
  local VXFER

  if [ $HOSTNAME = 'ZEBWL10D43164' ];then
    VXFER=$u/temp/.vimxfer
  else
    VXFER=$HOME/tmp/.vimxfer
  fi
  #                                                                           only absolute paths                          comment out for fc                    uncomment out for doubleclick
  history | grep -i "$1" | sed 's/#\+//' | grep 'cd ' | awk '{print $2, $3}' | grep '^cd [~/\$]' | tail -50 | sort | uniq | sed 's/^/#/' >| $VXFER | cat $VXFER | sed 's/^#//' ; echo "   note: $VXFER loaded"
}


# For PS1
parse_git_dirty() {
  [[ $(git status 2> /dev/null | tail -n1) != "nothing to commit (working directory clean)" ]] && echo "*"
}
parse_git_branch() {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/[\1$(parse_git_dirty)]/"
}


# Assumes $ /bin/updatedb --localpaths='/home/rsh86800/code' --prunepaths='/home/rsh86800/code/misccode/.git' --output='/var/lib/locatedb.code'
loc() {
  local cmd='locate --ignore-case --database=/var/lib/locatedb.code'
  local emsg="nothing found ($cmd)"
  local cnt=
  local grepme=

  if [ -z "$1" ];then
    echo '.bashrc usage: loc searchstr [(p)erl | (s)as | (o)ther code] [any_char_spawns_vim]'
  elif [ -z "$2" -a -z "$3" ];then
    $cmd "$1"
  elif [ -z "$3" ];then
    # Like my 'gone' utility
    if [ "$2" = p ];then
      grepme=perl
    elif [ "$2" = s ];then
      grepme=sas
    elif [ "$2" = o ];then
      grepme=misccode  # dummy to search all and allow any_char_here_spawns_vim
    else
      grepme=$2
    fi
    cnt=$($cmd "$1" | grep $grepme)
    if [ ! -z "$cnt" ]; then
      $cmd "$1" | grep $grepme
    else
      echo $emsg
    fi
  else
    # Like my 'gone' utility
    if [ "$2" = p ];then
      grepme=perl
    elif [ "$2" = s ];then
      grepme=sas
    elif [ "$2" = o ];then
      grepme=misccode  # dummy to search all and allow any_char_here_spawns_vim
    else
      grepme=$2
    fi
    cnt=$($cmd "$1" | grep $grepme)
    if [ ! -z "$cnt" ]; then
      vi -p `$cmd "$1" | grep $grepme`
    else
      echo $emsg
    fi
  fi
}


function encode() { echo -n $@ | perl -pe's/([^-_.~A-Za-z0-9])/sprintf("%%%02X", ord($1))/seg'; }
function google() { w3m http://www.google.com/search?hl=en#q="`encode $@`" ;}

# Generic Functions end


#-------------------
# Cygwin  #{{{1
#-------------------
# Debug from CMD w/o sourcing this file:
# c:\cygwin\bin\rxvt.exe -geometry 80x40+250+175 -fn "Andale Mono-12" -e /bin/bash --norc
case "$OSTYPE" in
  CYGWIN*|cygwin*)
    ###if [ -z $NONINTERACTIVE ]; then
      ###case "$HOSTNAME" in
        ###'ZEBWL06A16349' | 'sati' ) if test -e $HOME/bin/ck4blink; then $HOME/bin/blink& fi
      ###esac
    ###fi

    #-------------------
    # Export Cygwin  #{{{2
    #-------------------
    # For drives not mounted by Cygwin.  Allows easier completion e.g. $ cd $c/temp/foo<TAB>
    export a=/cygdrive/a
    export c=/cygdrive/c
    export d=/cygdrive/d
    export e=/cygdrive/e
    export f=/cygdrive/f
    export g=/cygdrive/g
    export h=/cygdrive/h
    export u=/cygdrive/u
    export x=/cygdrive/x
    export y=/cygdrive/y
    export z=/cygdrive/z
    export CYGWIN=nodosfilewarning  # MS-DOS style path detected: u:/tmp/bdfCURR.rtpsh005
    export CVSROOT=$HOME/repository
    # Must not be in General section b/c SunOS cron.
    export PATH=$HOME/bin:/usr/bin:/bin:$PATH
    export PERLLIB=$HOME/perllib
    export LANG=en_US
    # Lowercase the fscking Windows generated uppercase hostname.
    ###export LCHOSTNAME="`echo ${HOSTNAME} | perl -ne 's/(.*)/\L$1\E/;print'`"
    export LCHOSTNAME="`echo ${HOSTNAME} | tr [A-Z] [a-z]`"
    # The echo -ne "\033]0;${PWD}\007" causes rxvt titlebar to show PWD.
    # '\[ ... \]' says "ignore this material while calculating the size of the prompt".
    # We only want hostname's first 4 chars to avoid cluttering the titlebar.
    # Calling stoppedjobs() is too expensive on parsifal
    ###export PROMPT_COMMAND='echo -ne "\033]0;${LCHOSTNAME:0:4}:${PWD}\007";'
    ###export PROMPT_COMMAND='history -a;set_prompt_colors; echo -ne "\033]0;${LCHOSTNAME:0:4}:${PWD}\007";'
    # Needed to display path in menu titlebar.  TODO still need the history hack?
    # Want our history appended (-a) and other term's history merged into ours (-n)
    ###export PROMPT_COMMAND='history -a; history -n; echo -ne "\033]0;${LCHOSTNAME:0:4}:${PWD}\007";'
    export PROMPT_COMMAND='history -a; echo -ne "\033]0;${LCHOSTNAME:0:4}:${PWD}\007";'
    # Triple clickable noop prompt.  WinXP==CYGWIN_NT-5.1 W2K==5.0 
    ###if [ "${OSTYPE}" = 'CYGWIN_NT-5.1' ]; then
      ###export PS1='${fg_darkgray}\j ${fg_greenbold}\u@${LCHOSTNAME}${fg_darkgray}$(parse_git_branch) \W/ \d \t ${normal} \n\$ '
    ###export PS1='${fg_darkgray}\j ${fg_greenbold}\u@${LCHOSTNAME}${fg_darkgray} \W/ \d \t ${normal} \n\$ '
    ###else
      # Not sure why the escapes break WinXP.
      # TODO won't go to 2nd line using this
      ###export PS1=': `stoppedjobs`${prompt_beg}${USERNAME}@${LCHOSTNAME:0:8}${prompt_end}; '
      # TODO gets repeated chars during backspacing under tab completion, have
      # to remove the '\['s
      ###export PS1=': `stoppedjobs`\[${prompt_beg}\]${USERNAME}@${LCHOSTNAME:0:8}\[${prompt_end}\]; '
    ###fi
    export PS1='${fg_darkgray}\j ${fg_greenbold}\u@${LCHOSTNAME}${fg_darkgray}$(parse_git_branch) \W/ \d \t ${normal} \n\$ '
    export PS2=' '  # allow multiple line copy to clipboard 
    export TEMP=/cygdrive/c/temp
    ###export TERM=rxvt  # for cygwin 1.3.10 so that w3m restores upon exiting
    ###export TERM=cygwin
    export VIMSTATUSL="${USERNAME}@`echo ${HOSTNAME} | tr [A-Z] [a-z]`"

    #-------------------
    # Functions Cygwin  #{{{2
    #-------------------
    ###srcb() {
      ###source $HOME/.bashrc
      ###jobs
      # TODO parse `jobs` to figure out which %1, %2... is blink, then kill it
      # automatically
      ###echo 'Now figure which blink to remove (`kill %2` copied to clipboard)...'
      ###echo 'kill %2' | putclip
    ###}


    # Use Vim as man viewer to get color.  2006-10-26 col.exe is in ~/bin
    function vman {
      `which man` $* | col -bxp | `which view` -u \
       $HOME/code/misccode/.vimrc.more -c 'set ft=man nomod nolist ignorecase' -
    } 

###    function vimpdoc {
###      `which perldoc` -Tu $* | col -b | `which view` -u \
###                 $HOME/code/misccode/.vimrc.more -c 'set ft=pod nomod nolist' -
###    } 


    # arch() - backup (aka archive) files which have changed in the last N
    # days.  Number of days always INCLUDES TODAY.
    #
    # Copies of arch and unarch tarballs should exist in $TMP as audit trail 
    #
    # Without args, it assumes today is sometime during the workweek and will
    # calculate the days to backup from Monday to current day.  This won't
    # work for the weekend backups.  So use arch -d3 on Sunday night to
    # capture Friday night thru Sunday.
    #
    # 6 5 4 3 2 1
    # S M T W T F S
    # $ arch -d6  run on Friday afternoon will capture changes made today back
    # thru (and including) Sunday.
    #
    # Keep this function in .bashrc or it will fail when it attempts to back
    # itself up.  
    #
    # TODO remove REMOVETHIS__ markers after copying the markers to floppy to
    # avoid accidental deletions
    arch() {
      local now=`date +%Y%m%d`  # e.g. 20040922
      # Use last Sunday unless -d switch is passed to override later.
      local dayspast=`date +%w`   # e.g. Monday is 1, Tuesday is 2, ...

      # Path relative to $HOME.  DON'T use local here.
      f=(.bashrc .vimrc) 
      # Timestamp search descends into all subdirs of these dirs.
      ###d=(readme code)
      d=(code)
      if [ $HOSTNAME = 'sati' ]; then
        drv=f
        archdrv=/cygdrive/$drv/arch
      elif [ $HOSTNAME = 'ZEBWL06A16349' ]; then
        drv=e
        archdrv=/cygdrive/$drv/arch
      else
        echo .bashrc arch ERROR: do not know about this hostname: "$HOSTNAME"
        echo                     add hostname to arch
        echo press enter to quit
        read
        exit 1
      fi

      while getopts uUd: the_option; do
        case "$the_option" in
          u | U )  # Unarch (unpack) the tarball.
                   echo '%~%~%~%~%~%~%~%~%~%~%~%~ua~%~%~%~%~%~%~%~%~%~%~%~%~%~%~%~'
                   # If not arch'd today, prompt for confirmation to make sure
                   # we don't untar an old tarball by accident.
                   tnow=`date +%e`
                   ttball=`ls -l $archdrv/arch.tar.gz | awk '{print $7}'`
                   if [ $tnow != $ttball ]; then
                     echo -n 'Tarball date: '
                     tstamp=$(find $archdrv/arch.tar.gz -printf "%TA, %TB %Td" )
                     echo $tstamp
                     echo -n "Today's date: "
                     date '+%A, %B %d'
                     echo -n 'ok? (ctrl-c to abort) '
                     read
                   fi
                   if ! [ `cp $archdrv/arch.tar.gz $TMP/unarch${now}.tar.gz` ]; then
                     ###echo "Unarching $TMP/unarch${now}.tar.gz to c: and $archdrv..."
                     echo "Unarching $TMP/unarch${now}.tar.gz to c: ..."
                     (
                      cd $HOME || return 1
                      tar xvfz $TMP/unarch${now}.tar.gz || return 1
                      # Also synchronize jumpy for backup purposes
                      # TODO swiss jump too small 2007-07-09 
                      ###cd /cygdrive/$drv/cygwin/home/bheckel/ || return 1
                      ###tar xfz $TMP/unarch${now}.tar.gz || return 1
                     )
                     if [ $HOSTNAME = 'sati' ]; then
                       echo "Running allup -s to transfer to sverige..."
                       $HOME/bin/allup -s
                     fi
                   else
                     echo "ERROR: $FUNCNAME cannot cp $TMP/unarch${now}.tar.gz"
                   fi

                   # Make sure we don't miss any files copied by hand.
                   ls -la $archdrv

                   # Sysinternals version of sync
                   $HOME/bin/sync -r $drv  # flush
                   ###$HOME/bin/sync -e $drv  # eject

                   # Clean up rmv'd files.
                   if [ -e $HOME/bin/clean_synch ]; then
                     echo "${fg_purple}Running $HOME/bin/clean_synch ...${normal}"
                     $HOME/bin/clean_synch
                   else
                     echo "warning: $HOME/bin/clean_synch is not available!"
                   fi
                   return 0
                   ;;  # end of unarch
              d )  dayspast="$OPTARG"   # user requested N days of backup
                   ;;
              * )  echo 'Usage: arch [-u -dN]'
                   return 1
                   ;;
        esac
      done # processing switches, if any

      # If we reach there were no switches passed, it's during the workweek so
      # just arch it.

      echo "${fg_redbold}Make sure USB drive is mounted${normal}"
      echo '+»«.»«.»«.»«.»«.»«.»«.»«.»«.»«.»«.»«.»«.»«.»«»«.»«.»«.»«.»«.»«.»«.»«.»«.»«.»«+'

      (
       cd $HOME
       echo " Now tarballing: "
       echo -n $fg_yellow
       ###for the_obj in ${d[@]} ${f[@]}; do
       for the_obj in ${d[@]}; do
         echo "$the_obj/ "
       done
       for the_obj in ${f[@]}; do
         echo "$the_obj "
       done
       echo -n $normal
       echo "...touched during the last $dayspast day(s) (using -daystart)...looking for new files..."
       ###CYGWIN=ntsec  # for 700 permissions when ssh from cdc box
       # Safe for filenames with spaces if use find's -print0 and xarg's -0
       find ${f[@]} ${d[@]} -daystart \( -type f -o -type l \) -mtime \
            -$dayspast ! -name '*.*sw[op]' -print0 | xargs -0 tar cvfz \
	    $TMP/arch${now}.tar.gz
       echo
       echo '+»«.»«.»«.»«.»«.»«.»«.»«.»«.»«.»«.»«.»«.»«.»«»«.»«.»«.»«.»«.»«.»«.»«.»«.»«.»«+'
      )

      # Check for availability of drive before proceeding.
      if ! ( cd $archdrv ); then
        echo If drive $archdrv is really not available, \
             edit .bashrc otherwise check current mounts.  Press ctrl-c
        read
      else
        cp $TMP/arch${now}.tar.gz $archdrv/arch.tar.gz
        # For allup a
        cp $TMP/arch${now}.tar.gz $TMP/arch.tar.gz
      fi
       
      ck1=`cksum $TMP/arch${now}.tar.gz | awk '{print $1}'`
      ck2=`cksum $archdrv/arch.tar.gz | awk '{print $1}'`
      if [ $ck1 != $ck2 ]; then
        echo -n "$FUNCNAME: $fg_redbold cksum FAILURE! $arch${now}.tar.gz $normal may "
        echo 'have floppy trouble.  Continuing...'
      else
        if [ -e "$HOME/bin/align" ]; then
          align "$TMP/arch${now}.tar.gz" '===> checksums agree' 30
        else
          printf " %s \t\t\t\t===> checksums agree\n" arch${now}.tar.gz
        fi
        echo ${fg_purple}confirmation of uncorrupted tarball...${normal}
        tar tfz $archdrv/arch*
      fi

      # Sysinternals version of sync
      $HOME/bin/sync -r $drv  # flush
      # TODO causes corruption after our test for uncorruptedness?
      ###$HOME/bin/sync -e $drv  # eject

      return 0
    } 

    # end Functions Cygwin

    #-------------------
    # Alias Cygwin  #{{{2
    #-------------------
    alias by=logout  # like FTP and SAS
    alias bye=logout
    alias catput=$HOME/code/misccode/catput.sh
    # This assumes $TEMP is defined to C:\temp above for Cygwin vim/gvim issues (can't reside in Generic section, normal unix uses ~/tmp)
    alias d12="(cd $TEMP;vi -d 1 2)"
    alias d13="(cd $TEMP;vi -d 1 3)"
    alias d123="(cd $TEMP;vi -d 1 2 3)"
    alias d34="(cd $TEMP;vi -d 3 4)"
    alias datecalc=$HOME/code/perl/datecalc
    alias daystil=$HOME/code/misccode/daystil
###    alias =clear
    alias cygwin=$HOME/code/misccode/cygwin.bat  # norc bat version must be doubleclicked
    # rsynch of tobuddha/ will *copy* files symlinks point to from parsifal.
    ###alias budrsync='rsync -avz /home/bheckel/code/ root@buddha:/home/bheckel/code && rsync -avzL /home/bheckel/tobuddha/ root@buddha:/home/bheckel/tobuddha'
    # Cygwin fix b/c ck4suspend screws up the commandline somehow.  Use the
    # real fg for e.g. fg %2
    alias f='fg; echo'
    alias gv=gvim
    # Allow output to be triple clicked as a noop.
    ###alias h='history|tail -20|perl -pe "s/(\d+)(.*)/: \1; \2/"'
    alias h='history|tail -20'
    alias l='ls -GFw80 --color=none'   # for speed in Cygwin
    # Elim . .., owner and group info on Cygwin.
    alias ll='ls -FloGg --color=auto'
    alias lla='ls -FlAo --color=auto'
    # Long prompt, search match from near top, search skip screen, statusline,
    # pickup ANSI colors, search ignores case
    # Don't use export LESS='-M-j10$-a-P%f$-R-i-F' -it breaks loc()
    # Cygwin 1.7 instead of LANG=en_US; export LANG in .bash_profile
###    alias man="LANG=c man"
    ###alias m='less -M -j10$ -a -P%f$ -R -i'
    alias m="less -FRSX"  # don't use less if it fits in the window
    # Present Working Windows Directory
    alias pwwd='cygpath -w "`pwd`"'
    ###alias runllg="w3m -no-cookie -dump_source 'http://rtpsawn321/links/runllg.asp?action=Run+LLG'|grep '^LLG'"
###    alias runllg="w3m -no-cookie -dump_source 'http://rtpsawn321/links/runllg.asp?action=Run+LLG'|grep '^LLG' ; grep ERRMSG /cygdrive/x/SQL_Loader/Logs/LGI.log || echo fail"
    alias sas="c:/Program\ Files/SAS\ Institute/SAS/V8/sas.exe"
    ###alias sas8="c:/Program\ Files/SAS\ Institute/SAS/V8/sas.exe"
    ###alias sas9="c:/Program\ Files/SAS/SAS\ 9.1/sas.exe"
###    alias sasdate=$HOME/code/misccode/sasdate
    alias sasrun=$HOME/code/misccode/sasrun
    alias sensible-browser="/cygdrive/c/Program\ Files/mozilla\ firefox/firefox.exe"
###    alias usb="$HOME/bin/USB_Disk_Eject /removename '*LEXAR'"
###    alias usbe="$HOME/bin/USB_Disk_Eject /removeletter E"
    alias uvi=$HOME/code/perl/uvi  # don't change timestamp
    alias v="vim -u $HOME/code/misccode/.vimrc.more"  # alternative to 'm'
    alias vi=vim
    # Poor-man's gvim in an xterm.
###    alias vig='rxvt -geometry 80x50+250+50 +sb -fn "Andale Mono-12" -e vi -c start&'

    # Avoid nullglob or e.g. ls k* will show all files if no k* files exist.
    shopt -s cdspell checkhash checkwinsize cmdhist huponexit \
             histappend cdable_vars

    # Needed for `stty sane` and possibly for older versions of Cygwin to
    # avoid messing up Vim.
    ###stty erase ^H intr ^C kill ^K
    # Tab completion after typing 'cd ' should show dirs only.  See also
    # FIGNORE for related completion restrictions.
    complete -d cd

    ###umask 022
  ;; # end Cygwin

   #------------------
   # SunOS  #{{{1 
   #------------------
  'SunOS')
     #------------------
     # Export SunOS  #{{{2 
     #------------------
     export EDITOR=vi
     ###export PROMPT_COMMAND='set_prompt_colors; echo -ne "\033]0;`stoppedjobs`${HOSTNAME:0:6}:${PWD}\007"'
     export PROMPT_COMMAND='echo -ne "\033]0;`stoppedjobs`${HOSTNAME:0:6}:${PWD}\007"'
     # Set colors in set_prompt_colors(), not here.
     ###export PS1='\[${fg_darkgray}\]:\[${normal}\] `stoppedjobs`\[${prompt_beg}\]$USER@${HOSTNAME:0:8}\[${prompt_end}\]\[${fg_green}\]\$\[${fg_darkgray}\];\[${normal}\] '
     ###export PS1=':`stoppedjobs`$USER@${HOSTNAME:0:8}; '
     export PS2=' '  # allow multiple line copy to clipboard 
     export VIMSTATUSL="${USER}@`echo ${HOSTNAME} | tr [A-Z] [a-z]`"

     #--------------
     # Alias SunOS  #{{{2 
     #------------------
     ###alias got='go -t '
     alias jam='ps -eaf | grep `whoami`'
     alias l='ls -F'
     alias la='ls -FA'
     alias ls='ls -F'
     alias ll='ls -Fl'
     alias lla='ls -FlA'
     alias m=less
     export PATH=$HOME/bin:$PATH

     # Box specific differences:

     if [ $HOSTNAME = 'sunstat' ]; then
       alias sas='/apps/sas912/sas'
     else
       alias sas='/apps/sas8.2/sas'
       alias sas8='/apps/sas8.2/sas'
       alias sas9='/apps/sas912/sas'
     fi

     if [ $HOSTNAME = 'buddha' ]; then
       # Leave / as root's home for things like .Xauthority, etc.
       export LD_LIBRARY_PATH=/opt/sfw/lib:/opt/csw/lib:/usr/local/lib
       # TODO is this ok?
       export MANPATH=$MANPATH:/opt/man:/opt/sfw/man:/opt/csw/man:/usr/openwin/man
       export PATH=$PATH:/opt/bin:/opt/sfw/bin:/opt/csw/bin:/usr/ccs/bin
       # TODO run once only and only if X is running, but don't think it's
       # more than an annoyance if left as is
       /usr/openwin/bin/xmodmap /opt/share/xmodset

       alias bunzip2=/opt/csw/bin/bunzip2
       alias hf='hiber -nm off'
       alias ho='hiber -nm on'
       alias ls='gls -F --color'
       # Assumes this has been run first
       # LD_LIBRARY_PATH=/opt/mozilla/lib:/opt/sfw/lib:/opt/csw/lib
       # TODO LD_LIBRARY_PATH won't work inside shell script, must run from
       # command line like this:
       # export LD_LIBRARY_PATH=/opt/mozilla/lib:$LD_LIBRARY_PATH && moz
       ###alias moz=/opt/mozilla/mozilla
       alias moz='echo do not use moz for now'
       alias whoami=gwhoami
       alias x='rxvt -sr -sk -cr green -pr blue -sl 999 -fn "-sun-*-*-*-*-12-*-*-*-*-*-*-*-*" -bg black -fg wheat -geometry 80x33 -e bash -i'
     fi

     if [ $HOSTNAME = 'daeb' ]; then
       export PATH="$HOME/bin:/opt/bin:/usr/bin:/usr/local/bin:/bin:/opt/sfw/bin:/usr/ucb/:/usr/ccs/bin:/opt/mysql/bin"
       # Used at least by 'Bash Prompt Here' and jam.
       export USER=`/usr/ucb/whoami` 
       # For at least mysql
       export LD_LIBRARY_PATH=/opt/sfw/lib
       export MANPATH=$MANPATH:/opt/man:/opt/sfw/man:/usr/openwin/man
       # Run system check every other day.
       if [ `date | awk '{print $3}' | perl -e '$x=<>; $y=($x%2); END{print $y}'` = 0 ]; then
         echo
         \ls -l /opt/apache/logs/*_log
         echo
         df -k
         echo
         uptime
         who
         echo
         last|grep -v bheckel|head -9
       fi
     fi

     if [ $HOSTNAME = 'tstdev' ]; then
       # For make, etc. {{{
       export EDITOR=/opt/SUNWspro/contrib/contrib6/vim5.6/bin/vim
       export PATH=$PATH:/usr/ccs/bin/
       export VIM=/opt/SUNWspro/contrib/contrib6/vim5.6/share/vim/vim56
       export VISUAL=/usr/bin/vi  # for cron
       alias jam="ps -eaf|grep `whoami`"
       alias vi="/opt/SUNWspro/contrib/contrib6/vim5.6/bin/vim"
     fi

     if [ $HOSTNAME = 'anicca' ]; then
       export PATH=$PATH:/usr/local/bin:/opt/sfw/bin
       alias vi=vim
     fi

     stty erase ^? intr ^C kill ^K

     shopt -s cdspell 

     umask 027
  ;; # end SunOS


  #-------------------
  # Linux  #{{{1
  #-------------------
  linux-gnu | Linux)
      # ChromeOS  TODO also check USER?
      if [ $HOSTNAME = 'localhost' ]; then
        # Make sure we can write to this bitch
        sudo mount -i -o remount,exec /home/chronos/user
        cd ~

        # Optionally start Dropbox if it's not running.
        # http://gabeortiz.net/2011/how-to-get-dropbox-working-on-a-cr48-google-chrome-netbook/
        if [ -z "$(pgrep dropbox)" ] && [ -d ~/.dropbox-dist ]; then
          echo -n 'Start Dropbox? '
          read yn
          if [ "$yn" = 'y' ];then
             ~/.dropbox-dist/dropboxd &
          fi
        fi

        alias dropbox='~/.dropbox-dist/dropboxd &'
        ###alias bc=python
        ###alias loc='sudo locate -i'
        alias vi='~/bin/vim -u ~/code/misccode/_vimrc'

        export PATH=$PATH:~/bin
        export VIMRUNTIME=/home/chronos/user/.vim
        ###export PYTHONPATH=/home/chronos/user
        ###export PYTHONHOME=$PYTHONPATH
      fi

      # Use: bigshell FONTSIZE (where fontsize defaults to 16).  Gil Levy
      function bigshell() {
        fontsize=${1:-16}
        urxvt -fn "xft:DejaVu Sans Mono:pixelsize=$fontsize" -bc -fb "xft:DejaVu Sans Mono:pixelsize=$fontsize" -tn xterm -bg black -fg grey +sb -color0 "#000000" -color1 "#9e1828" -color2 "#4f874f" -color3 "#968a38" -color4 "#5d5da0" -color5 "#963c59" -color6 "#418179" -color7 "gray" -color8 "gray40" -color9 "#cf6171" -color10 "#c5f779" -color11 "#fff796" -color12 "#4186be" -color13 "#cf9ebe" -color14 "#71bebe" -color15 "white" -e /usr/bin/crosh
      }
      # end ChromeOS

      # Virtual Box
      if [ $HOSTNAME = 'samadhi' ]; then
        sudo mount -t vboxsf -o uid=1000,gid=1000 code /home/bheckel/code
        sleep 3
        source ~/code/misccode/_bashrc
      fi

      if [ $HOSTNAME = 'redhat' ] && [ -e 'EMIAKEFLAG' ]; then
        # VMWare loses track of the date while suspended.  This pops-up
        # /usr/X11R6/bin/vmware-toolbox to synchronize the guest with the host
        $HOME/bin/dtsynch
      fi

      # CR48
      if [ $HOSTNAME = 'ubuntu' ]; then
        ###export PATH=$PATH:/home/ubuntu/android_sdk_linux_m3-rc22a/tools
        # Don't want autostart so that at least this box won't start modifying immediately in case of trouble.
        alias dropbox='~/.dropbox-dist/dropboxd &'
        alias vi='vim -u ~/code/misccode/_vimrc'
      fi

      # TODO if not running (via fluxbox) start dropbox and nm-applet
      if [ $HOSTNAME = 'yoniso' ]; then
        # Assumes we have saved the gsk attachment as ~/Downloads/c
        alias gskfrom='cd ~ && tar xvfz ~/Downloads/c && mv ~/Downloads/{c,c.PREV} && find -L ~/code -perm 000|xargs chmod 755'
        # Assumes we have recent work ready to mail to gsk as c.NEW
        alias gskto='cd ~ && find -L code/ -type f -newer ~/Downloads/c.PREV |grep -v '/.git/'|grep -v '.swp'|xargs tar cvfz ~/Downloads/c.NEW'
        alias nexus='sudo mount -t vfat /dev/sdb /media/Nexus -o uid=1000,gid=1000,utf8,dmask=027,fmask=137; mount|grep "^/dev/sd"; echo "sudo umount /media/Nexus"'
      fi

      export PROMPT_COMMAND='history -a; echo -ne "\033]0;${HOSTNAME:0:4}:${PWD}\007";'
      export PS1='${fg_darkgray}\j ${fg_greenbold}\u@${HOSTNAME}${fg_darkgray}$(parse_git_branch) \W/ \d \t ${normal} \n\$ '

###      export VIMSTATUSL="${USER}@`echo ${HOSTNAME} | tr [A-Z] [a-z]`"
      export VIMSTATUSL="${USER}@`echo ${HOSTNAME}`"

      #----------------
      # Alias linux  #{{{2 
      #----------------
      if [ $HOSTNAME = 'localhost' ]; then  # cr48
        # Using static 7zip instead of the uncompilable unzip
        alias unzip='~/bin/7za x '
      fi

      if [ $HOSTNAME = 'yoniso' ]; then 
        ###if [ -z "$(pgrep conky)" ]; then
          ###conky -x 5 -y 0 &
        ###fi
        ###alias sb='sudo mount -t vfat /dev/sdb1 /media/Lexar -o uid=1000,gid=1000,utf8,dmask=027,fmask=137 && mount|grep "^/dev/sd" && sleep 5 && echo && SyncBackSE.exe && sleep 5 && echo && sudo umount /media/Lexar && mount|grep "^/dev/sd"'
        alias tide="~/adt-bundle-linux-x86/sdk/platform-tools/adb -d forward tcp:8080 tcp:8080 && telnet -e '' 127.0.0.1 8080"
      fi

      alias d12="(cd ~/tmp; vi -d 1 2)"
      alias d13="(cd ~/tmp; vi -d 1 3)"
      alias d123="(cd ~/tmp; vi -d 1 2 3)"
      alias d34="(cd ~/tmp; vi -d 3 4)"
      ###alias sqlplus=/usr/lib/oracle/xe/app/oracle/product/10.2.0/server/bin/sqlplus
      ###alias moz='export DISPLAY=158.111.250.170:0.0; mozilla&'

      shopt -s cdspell checkhash cmdhist dotglob histappend

      stty erase ^? intr ^C kill ^K

      umask 022
  ;; # end linux


  #-------------------
  # NetBSD  #{{{1
  #-------------------
  'netbsd')
     # TODO be careful this is only expecting sdf, add hostname filter
      ###if [ -z $NONINTERACTIVE  ]; then
        # Used  touch ~/.hushlogin  to shutup MOTD and it somehow affects
        # this.  No big loss.
        ###top -d 2 | col -b | grep states
        ###mailstat $HOME/.procmail/log
      ###fi

      #----------------
      # Export NetBSD  #{{{2 
      #----------------
      export EDITOR=/usr/pkg/bin/vim
      # For mutt on sdf at least
      export LANG=en_US.UTF-8
      export LC_TYPE=en_US.UTF-8
      export MAILCHECK=5
###      export PATH=$HOME/bin:$PATH
      export PATH=$HOME/bin:$PATH:/usr/pkg/bin
      # TODO colors force lines to not wrap to new line
      ###export PS1='\[${fg_darkgray}\]:\[${normal}\]`stoppedjobs`\[${prompt_beg}\]$(whoami)@${HOSTNAME:0:8}\[${prompt_end}\]${fg_lightgray}\]\$${fg_darkgray}\];\[${normal}\] '
      ###export PS1=': `stoppedjobs`$(whoami)@${HOSTNAME:0:8}$ '
      ###export PS1='${fg_darkgray}`stoppedjobs` ${fg_whitebold}\u@${HOSTNAME}${fg_darkgray} \W/ \d \t ${normal} \n\$ '
      export PS1='${fg_darkgray}\j ${fg_whitebold}\u@${HOSTNAME}${fg_darkgray} \W/ \d \t ${normal} \n\$ '
###      export PROMPT_COMMAND='set_prompt_colors; echo -ne "\033]0;`stoppedjobs`${HOSTNAME:0:6}:${PWD}\007"'
      export PROMPT_COMMAND='echo -ne "\033]0;`stoppedjobs`${HOSTNAME:0:6}:${PWD}\007"'
      export SURFRAW_text_browser=w3m
      export WWW_HOME=http://www.google.com
      export TERM=xterm
      export TZ=/usr/share/zoneinfo/US/Eastern
      #----------------
      # Alias NetBSD  #{{{2 
      #----------------
      alias bak=~/bin/bak
      # TODO if sdf boxes only
      alias crontab=mkcron
      # Mnemonic 'after my alias "f" to fg'
      ###alias g='screen -r'
      ###alias got='go -t '
      alias jam='ps -aux | grep $USER'
      alias la='\ls -la'
      alias ls='\ls -F'
      alias ll='\ls -Fl'
      alias sha1sum='cksum -a sha1 '
      alias ve="vi ~/.vimrc"
      alias vi='/usr/pkg/bin/vim'

      umask 077
      # This should be in .bash_logout:
      ## Flush so that mail received during this login session is not counted
      ## at next login.
      # mailstat $HOME/.procmail/log 1>/dev/null

      #----------------
      # Functions NetBSD  #{{{2 
      #----------------

      shopt -s cdspell checkhash checkwinsize cmdhist huponexit \
	             histappend cdable_vars

  ;; # end NetBSD

  #-------------------
  # Mainframe  #{{{1
  #-------------------
  'OS/390')
      #-----------------
      # Export OS/390  #{{{2 
      #-----------------
      export EDITOR=vim
      export PATH=$HOME/bin:/IBMGNU/bin:/usr/local/bin:$PATH
      export PROMPT_COMMAND='set_prompt_colors'
      export PS1=': `stoppedjobs`\[${prompt_beg}\]$(whoami|tr A-Z a-z)@ip01\[${prompt_end}\]\[${fg_green}\]\$\[${normal}\]; '
      # Mandatory for dtelnet
      export TERM=xterm
      #-----------------
      # Alias OS/390  #{{{2 
      #-----------------
      # whoami returns OMVSKERN but $LOGNAME is bqh0
      unalias ls
      alias bc="bc -l"  # allow floating point calcs
      alias l='ls -F'
      alias ls='ls -F'
      alias la='ls -aF'
      alias ll='ls -lF'
      alias lt='ls -ltF | head -n20'     # latest twenty
      alias got='go -t '
      alias vi=vim

      umask 022
  ;; # end OS/390

  * )  #   
      ###if [ -z $NONINTERACTIVE ]; then
        echo "$HOME/.bashrc: Unknown OSTYPE.  May need to edit .bashrc"
      ###fi
  ;;
esac #}}}
#}}}1

if [ -e $HOME/code/misccode/_project.bashrc ]; then
  # Project-specific or security related additions
  source $HOME/code/misccode/_project.bashrc
fi
